all:
	gcc -o test100.out test_score_100.c
	gcc -o test0.out test_score_zero.c
	gcc -o testnon.out test_score_normal.c
	gcc -o testSG_errG.out test_SET_GET_errGET.c
	gcc -o testSG_errS.out test_SET_GET_errSET.c
	gcc -o testSG.out test_SET_GET.c

clean:
	rm -f *.out
	rm -f *.o 